# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "resort-bjones"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Oriol Gual", "Josep M. Bach", "Josep Jaume Rey", "Brian Jones"]
  s.date = "2011-12-14"
  s.description = "Positionless model sorting for Rails 3."
  s.email = "cbj@gnu.org"
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "lib/generators/active_record/resort_generator.rb",
    "lib/generators/active_record/templates/migration.rb",
    "lib/resort-bjones.rb",
    "lib/resort.rb",
    "lib/resort/version.rb",
    "resort-bjones.gemspec",
    "spec/generators/migration_spec.rb",
    "spec/resort_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/bjones/resort"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Positionless model sorting for Rails 3."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["< 3.2", ">= 3.0.5"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<bluecloth>, [">= 0"])
      s.add_development_dependency(%q<generator_spec>, ["~> 0.8.1"])
    else
      s.add_dependency(%q<activerecord>, ["< 3.2", ">= 3.0.5"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<bluecloth>, [">= 0"])
      s.add_dependency(%q<generator_spec>, ["~> 0.8.1"])
    end
  else
    s.add_dependency(%q<activerecord>, ["< 3.2", ">= 3.0.5"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<bluecloth>, [">= 0"])
    s.add_dependency(%q<generator_spec>, ["~> 0.8.1"])
  end
end

